#!/usr/bin/env python3
"""scripts/setup_langfuse.py — One-shot LangFuse credential generator.

Run via `make langfuse-up` (recommended) or directly::

    python scripts/setup_langfuse.py [--force]

What it does
------------
1. Generates cryptographically strong secrets:
   - NEXTAUTH_SECRET and SALT  (for the LangFuse server)
   - Organisation and project UUIDs
   - API key pair in LangFuse format (``pk-lf-<uuid>`` / ``sk-lf-<uuid>``)
   - A random admin password
2. Writes those secrets to ``.env.langfuse`` — Docker Compose reads this to
   seed the LangFuse server via ``LANGFUSE_INIT_*`` environment variables,
   so no manual account creation through the UI is ever needed.
3. Updates the project ``.env`` so the Python app connects immediately:
   ``LANGFUSE_ENABLED=true``, ``LANGFUSE_HOST``,
   ``LANGFUSE_PUBLIC_KEY``, ``LANGFUSE_SECRET_KEY``.

Idempotent
----------
Re-running without ``--force`` is a no-op if ``.env.langfuse`` already
exists — the existing credentials are simply re-synced into ``.env``.

Use ``--force`` to rotate **all** credentials.  This requires destroying the
LangFuse database volume (``make langfuse-reset``) because the previous
key pair will no longer exist on the new server initialisation.
"""

from __future__ import annotations

import argparse
import secrets
import sys
import uuid
from pathlib import Path

# ── Paths ──────────────────────────────────────────────────────────────────
REPO_ROOT = Path(__file__).resolve().parent.parent
ENV_LANGFUSE = REPO_ROOT / ".env.langfuse"
ENV_PROJECT = REPO_ROOT / ".env"

# ── ANSI colours (graceful fallback on non-TTY) ───────────────────────────
_USE_COLOR = sys.stdout.isatty()


def _c(code: str, text: str) -> str:
    return f"\033[{code}m{text}\033[0m" if _USE_COLOR else text


def _ok(msg: str) -> None:
    print(f"  {_c('32', '✔')}  {msg}")


def _info(msg: str) -> None:
    print(f"  {_c('36', '·')}  {msg}")


def _warn(msg: str) -> None:
    print(f"  {_c('33', '!')}  {msg}")


def _section(title: str) -> None:
    width = 60
    print()
    print(_c("1", title))
    print(_c("90", "─" * width))


# ── Secret generators ──────────────────────────────────────────────────────


def _hex(n: int = 32) -> str:
    """Return ``n`` random bytes as a lowercase hex string (2n chars)."""
    return secrets.token_hex(n)


def _lf_public_key() -> str:
    """LangFuse-style public key: ``pk-lf-<uuid4>``."""
    return f"pk-lf-{uuid.uuid4()}"


def _lf_secret_key() -> str:
    """LangFuse-style secret key: ``sk-lf-<uuid4>``."""
    return f"sk-lf-{uuid.uuid4()}"


def _password() -> str:
    """Generate a human-readable but strong random password."""
    return secrets.token_urlsafe(18)  # 18 bytes → 24-char base64url string


# ── .env.langfuse writer ───────────────────────────────────────────────────


def _generate_env_langfuse() -> dict[str, str]:
    """Generate all LangFuse server secrets from scratch."""
    return {
        "NEXTAUTH_SECRET": _hex(32),
        "SALT": _hex(32),
        "LANGFUSE_INIT_ORG_ID": str(uuid.uuid4()),
        "LANGFUSE_INIT_ORG_NAME": "AutoInsight AI",
        "LANGFUSE_INIT_PROJECT_ID": str(uuid.uuid4()),
        "LANGFUSE_INIT_PROJECT_NAME": "autoinsight",
        "LANGFUSE_INIT_PROJECT_PUBLIC_KEY": _lf_public_key(),
        "LANGFUSE_INIT_PROJECT_SECRET_KEY": _lf_secret_key(),
        "LANGFUSE_INIT_USER_EMAIL": "admin@autoinsight.local",
        "LANGFUSE_INIT_USER_NAME": "Admin",
        "LANGFUSE_INIT_USER_PASSWORD": _password(),
    }


def _write_env_langfuse(secrets_: dict[str, str]) -> None:
    """Write (or overwrite) the .env.langfuse file."""
    lines = [
        "# .env.langfuse — LangFuse server secrets",
        "# Generated by scripts/setup_langfuse.py — DO NOT COMMIT",
        "# Loaded by docker-compose.langfuse.yml via the env_file directive.",
        "",
        "# ── LangFuse server security ──────────────────────────────────────",
        f"NEXTAUTH_SECRET={secrets_['NEXTAUTH_SECRET']}",
        f"SALT={secrets_['SALT']}",
        "",
        "# ── Auto-seeded organisation ──────────────────────────────────────",
        f"LANGFUSE_INIT_ORG_ID={secrets_['LANGFUSE_INIT_ORG_ID']}",
        f"LANGFUSE_INIT_ORG_NAME={secrets_['LANGFUSE_INIT_ORG_NAME']}",
        "",
        "# ── Auto-seeded project ───────────────────────────────────────────",
        f"LANGFUSE_INIT_PROJECT_ID={secrets_['LANGFUSE_INIT_PROJECT_ID']}",
        f"LANGFUSE_INIT_PROJECT_NAME={secrets_['LANGFUSE_INIT_PROJECT_NAME']}",
        "",
        "# ── API keys (Python app uses these) ─────────────────────────────",
        f"LANGFUSE_INIT_PROJECT_PUBLIC_KEY={secrets_['LANGFUSE_INIT_PROJECT_PUBLIC_KEY']}",
        f"LANGFUSE_INIT_PROJECT_SECRET_KEY={secrets_['LANGFUSE_INIT_PROJECT_SECRET_KEY']}",
        "",
        "# ── Admin account ─────────────────────────────────────────────────",
        f"LANGFUSE_INIT_USER_EMAIL={secrets_['LANGFUSE_INIT_USER_EMAIL']}",
        f"LANGFUSE_INIT_USER_NAME={secrets_['LANGFUSE_INIT_USER_NAME']}",
        f"LANGFUSE_INIT_USER_PASSWORD={secrets_['LANGFUSE_INIT_USER_PASSWORD']}",
    ]
    ENV_LANGFUSE.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _read_env_langfuse() -> dict[str, str]:
    """Parse the existing .env.langfuse and return its key-value pairs."""
    result: dict[str, str] = {}
    for raw in ENV_LANGFUSE.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "=" in line:
            key, _, value = line.partition("=")
            result[key.strip()] = value.strip()
    return result


# ── Project .env updater ───────────────────────────────────────────────────


def _update_project_env(updates: dict[str, str]) -> None:
    """Update specific keys in the project .env, preserving all other content.

    Keys present in the file are updated in-place (preserving line order).
    Keys absent from the file are appended at the end.
    """
    if not ENV_PROJECT.exists():
        _warn(f"{ENV_PROJECT.name} does not exist — creating it.")
        ENV_PROJECT.write_text("", encoding="utf-8")

    lines = ENV_PROJECT.read_text(encoding="utf-8").splitlines()
    remaining = dict(updates)
    new_lines: list[str] = []

    for line in lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            new_lines.append(line)
            continue
        if "=" in stripped:
            key = stripped.split("=", 1)[0].strip()
            if key in remaining:
                new_lines.append(f"{key}={remaining.pop(key)}")
                continue
        new_lines.append(line)

    # Append any keys that were not already in the file
    if remaining:
        new_lines.append("")
        new_lines.append("# LangFuse — auto-configured by scripts/setup_langfuse.py")
        for key, value in remaining.items():
            new_lines.append(f"{key}={value}")

    ENV_PROJECT.write_text("\n".join(new_lines) + "\n", encoding="utf-8")


# ── Main ───────────────────────────────────────────────────────────────────


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate LangFuse credentials and configure the project.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help=(
            "Regenerate ALL credentials even if .env.langfuse already exists. "
            "Requires destroying the LangFuse database volume (make langfuse-reset)."
        ),
    )
    args = parser.parse_args()

    print()
    print(_c("1;36", "🔑  AutoInsight AI — LangFuse Setup"))
    print(_c("90", "─" * 60))

    # ── Step 1: Generate or load .env.langfuse ────────────────────────────
    _section("Step 1 · LangFuse server credentials")

    if ENV_LANGFUSE.exists() and not args.force:
        _ok(f"{ENV_LANGFUSE.name} already exists — loading existing credentials")
        _info("(use --force / make langfuse-reset to rotate credentials)")
        creds = _read_env_langfuse()
    else:
        if args.force and ENV_LANGFUSE.exists():
            _warn("--force: regenerating ALL credentials (old keys will be invalid)")
        else:
            _info("First run — generating cryptographically strong credentials")

        creds = _generate_env_langfuse()
        _write_env_langfuse(creds)
        _ok(f"{ENV_LANGFUSE.name} written")

    # ── Step 2: Sync into project .env ───────────────────────────────────
    _section("Step 2 · Project .env")

    project_updates = {
        "LANGFUSE_ENABLED": "true",
        "LANGFUSE_HOST": "http://localhost:3001",
        "LANGFUSE_PUBLIC_KEY": creds["LANGFUSE_INIT_PROJECT_PUBLIC_KEY"],
        "LANGFUSE_SECRET_KEY": creds["LANGFUSE_INIT_PROJECT_SECRET_KEY"],
    }
    _update_project_env(project_updates)
    _ok(f"{ENV_PROJECT.name} updated (LANGFUSE_ENABLED=true, keys synced)")

    # ── Step 3: Summary ───────────────────────────────────────────────────
    _section("Ready")
    _info("LangFuse UI:      http://localhost:3001")
    _info(f"Admin email:      {creds['LANGFUSE_INIT_USER_EMAIL']}")
    _info(f"Admin password:   {creds['LANGFUSE_INIT_USER_PASSWORD']}")
    _info(f"Public key:       {creds['LANGFUSE_INIT_PROJECT_PUBLIC_KEY']}")
    print()
    _ok("Docker Compose will now start and seed LangFuse automatically.")
    _ok("No manual account creation needed — credentials are pre-configured.")
    print()


if __name__ == "__main__":
    main()
