"""Compact structured context builders for downstream LLM agents.

These helpers turn rich pipeline artifacts into short, high-signal digests so
later agents do not need to re-read verbose markdown generated by earlier ones.
"""

from __future__ import annotations

from typing import Any


def _shape(profile_data: dict[str, Any] | None) -> tuple[int | str, int | str]:
    """Return ``(rows, cols)`` from either the current or legacy profile shape."""
    raw_shape = (profile_data or {}).get("shape", {})
    if isinstance(raw_shape, list):
        rows = raw_shape[0] if len(raw_shape) > 0 else "?"
        cols = raw_shape[1] if len(raw_shape) > 1 else "?"
        return rows, cols
    if isinstance(raw_shape, dict):
        return raw_shape.get("rows", "?"), raw_shape.get("cols", "?")
    return "?", "?"


def _stats(profile_data: dict[str, Any] | None) -> dict[str, Any]:
    """Return a normalized stats dict across current and legacy profile formats."""
    profile = profile_data or {}
    stats = profile.get("stats")
    if isinstance(stats, dict):
        return stats
    return {
        "duplicates_count": profile.get("duplicates", 0),
        "duplicates_pct": profile.get("duplicates_pct", 0.0),
        "total_missing_count": profile.get("total_missing_count", 0),
        "total_missing_pct": profile.get("total_missing_pct", 0.0),
        "memory_mb": profile.get("memory_mb", 0.0),
    }


def _iter_columns(profile_data: dict[str, Any] | None) -> list[dict[str, Any]]:
    """Return normalized column dicts across current and legacy profile formats."""
    columns_raw = (profile_data or {}).get("columns") or {}
    if isinstance(columns_raw, dict):
        normalized: list[dict[str, Any]] = []
        for name, info in columns_raw.items():
            if not isinstance(info, dict):
                continue
            item = dict(info)
            item.setdefault("name", str(name))
            normalized.append(item)
        return normalized
    if isinstance(columns_raw, list):
        return [dict(item) for item in columns_raw if isinstance(item, dict)]
    return []


def build_profile_digest(
    profile_data: dict[str, Any] | None,
    *,
    max_columns: int = 8,
) -> str:
    """Build a compact dataset-profile digest for downstream prompts."""
    if not profile_data:
        return "No structured profile available."

    rows, cols = _shape(profile_data)
    stats = _stats(profile_data)
    columns = _iter_columns(profile_data)

    important_columns = sorted(
        columns,
        key=lambda col: (
            float(col.get("missing_pct", 0.0) or 0.0),
            float(col.get("unique_pct", 0.0) or 0.0),
        ),
        reverse=True,
    )[:max_columns]

    lines = [
        f"Dataset: {rows} rows x {cols} columns",
        f"Missing: {float(stats.get('total_missing_pct', 0.0) or 0.0):.1f}%",
        f"Duplicates: {float(stats.get('duplicates_pct', 0.0) or 0.0):.1f}%",
        f"Memory: {float(stats.get('memory_mb', 0.0) or 0.0):.2f} MB",
    ]
    if important_columns:
        lines.append("Key columns:")

    for column in important_columns:
        name = str(column.get("name", "?"))
        dtype = str(column.get("dtype_category") or column.get("dtype") or "unknown")
        missing_pct = float(column.get("missing_pct", 0.0) or 0.0)
        part = f"- {name} ({dtype}, {missing_pct:.1f}% missing"

        mean_val = column.get("mean")
        std_val = column.get("std")
        unique_count = column.get("unique_count", column.get("unique"))
        if mean_val is not None and std_val is not None:
            part += f", mean={float(mean_val):.2f}, std={float(std_val):.2f}"
        elif unique_count is not None:
            part += f", {int(unique_count)} unique"

        top_values = column.get("top_values")
        if isinstance(top_values, dict) and top_values:
            top_key, top_val = next(iter(top_values.items()))
            part += f", top={top_key} ({top_val})"

        part += ")"
        lines.append(part)

    if len(columns) > len(important_columns):
        lines.append(f"- ... {len(columns) - len(important_columns)} more columns")

    return "\n".join(lines)


def build_insights_digest(
    insights: list[dict[str, Any]] | None,
    *,
    max_items: int = 6,
) -> str:
    """Build a concise digest of structured insights."""
    if not insights:
        return "No structured insights available."

    lines: list[str] = []
    for index, insight in enumerate(insights[:max_items], start=1):
        title = str(insight.get("title", "Untitled"))
        priority = str(insight.get("priority", "medium")).capitalize()
        category = str(insight.get("category", "general")).capitalize()
        observation = str(insight.get("observation", "N/A"))
        recommendation = str(insight.get("recommendation", "N/A"))
        lines.append(
            f"{index}. [{priority}] [{category}] {title}\n"
            f"   Observation: {observation}\n"
            f"   Recommendation: {recommendation}"
        )

    if len(insights) > max_items:
        lines.append(f"... and {len(insights) - max_items} more insight(s)")

    return "\n".join(lines)


def build_critiques_digest(
    critiques: list[dict[str, Any]] | None,
    *,
    max_items: int = 6,
) -> str:
    """Build a compact digest of critic verdicts and main weaknesses."""
    if not critiques:
        return "No critique summary available."

    lines: list[str] = []
    for index, critique in enumerate(critiques[:max_items], start=1):
        title = str(critique.get("insight_title", "Untitled"))
        verdict = str(critique.get("verdict", "partially_supported")).replace("_", " ")
        confidence = str(critique.get("confidence", "medium"))
        weakness = str(critique.get("weaknesses", "N/A"))
        alternative = str(critique.get("alternatives", "N/A"))
        lines.append(
            f"{index}. {title} — verdict={verdict}, confidence={confidence}\n"
            f"   Weaknesses: {weakness}\n"
            f"   Alternative: {alternative}"
        )

    if len(critiques) > max_items:
        lines.append(f"... and {len(critiques) - max_items} more critique(s)")

    return "\n".join(lines)


def build_confidence_digest(
    confidence_scores: list[dict[str, Any]] | None,
    *,
    max_items: int = 6,
) -> str:
    """Build a compact digest of uncertainty scores."""
    if not confidence_scores:
        return "No confidence summary available."

    lines: list[str] = []
    for index, score in enumerate(confidence_scores[:max_items], start=1):
        title = str(score.get("insight_title", "Untitled"))
        total = int(score.get("confidence_score", 0) or 0)
        level = str(score.get("confidence_level", "medium"))
        summary = str(score.get("summary", ""))
        lines.append(f"{index}. {title} — {total}% ({level})\n   {summary}")

    if len(confidence_scores) > max_items:
        lines.append(f"... and {len(confidence_scores) - max_items} more score(s)")

    return "\n".join(lines)
